server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaeldoug/exemplo-microservice-arq-si/config-repo
          basedir: target/config
          default-label: main
